### PR TITLE
Add missing ';'

### PR DESCRIPTION
**Pull request by Prometheus0000**

### CODE REVIEW

**Comment by Prometheus0000** [comment]
It builds, runs and prevents repairing the mutagenic frame, but also has 3323 modifications stuck?

**Comment by Rakdarian** [comment]
Why was it an issue to allow it to repair the mutagenic frame? Wasnt there a call to rebalance bees entirely since they're strictly worse then crops in the first place. I vaguely recall bart posting about that

**Comment by GTNH-Afx237v7** [comment]
Don’t do /mt reload, it gives errors all the time. If you have had that happen after a relaunch of the server, then there is an issue.

**Comment by Prometheus0000** [comment]
It's a bug, they're not supposed to be repairable, straight from the person who made them, alk. And you aren't supposed to transform items into other items, or repair fuel rods either.

/mt reload? I restarted the whole instance? So it's about the MT scripts?

**Comment by botn365** [comment]
bees suck to much for this to make any difrence

**Comment by GTNH-Afx237v7** [comment]
I identified The error message as originating from Minetweaker (have seen it various times when I started). 
There should also be a Minetweaker log available, maybe there is more info available in there.

**Comment by Prometheus0000** [comment]
Restarting it now, but I don't see a previous MT.log (or similar) file in the logs folder?

**Comment by Prometheus0000** [comment]
Not only has this killed my test world, it logged me out of my account in MMC, grah.

And now no errors too? And it's the right version since it still disables the fixing. Here's the log anyway
[minetweaker.log](https://github.com/GTNewHorizons/ThaumicHorizons/files/5373890/minetweaker.log)

**Comment by GTNH-Afx237v7** [comment]
Don’t see anything immediately obvious in the log... plus the change in code should not have an influence on Minetweaker...had any luck restarting everything?

**Comment by Prometheus0000** [comment]
Like I said, it seemed to work fine after I got over the level.dat dying and having to relogin to MMC. I also tried redoing my 2.0.9.1a dev install, with no problems, in case it was something else.

**Pull request merged**
