### PR TITLE
validate player has the prereq self infusion before doing what player has requested

### PR DESCRIPTION
**Pull request by Glease**

### CODE REVIEW

**Review by Alastors — APPROVED** [review]
Yeah looks good!

**Comment by Glease** [comment]
Actually there is one more issue... might need another review

**Comment by Alastors** [comment]
Lmfao that's aight, just ping me when you're done

**Comment by Glease** [comment]
@Alastors nah that's the last one. PR is now ready

**Review by Alastors — APPROVED** [review]
Lmfaoooo yeah still looks good to me, I'm sure it'll help with future security concerns

**Pull request merged**
