### PR TITLE
New lens textures

### PR DESCRIPTION
**Pull request by Ethryan**
As requested by dev,
Connected to:
- [#13735 New Lenses for Goggles of Revealing](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13735)

As new textures.

### CODE REVIEW

**Comment by Alastors** [comment]
Let's gooooooo

**Review by Alastors — APPROVED** [review]

**Comment by Ethryan** [comment]
I'm keeping the psds here since that makes editing the lenses possible.

**Comment by Dream-Master** [comment]
PSD files are nice for edit yes but put it  into resource is a bad idea. We don't want huge mods which carry files the mod itself not use.

**Comment by Ethryan** [comment]
They are in a new folder, outside of source
@Dream-Master

**Comment by Dream-Master** [comment]
ok then it is fine

**Pull request merged**
