### PR TITLE
Code cleanup

### PR DESCRIPTION
**Pull request by chill-was-taken**
This PR mostly applies IntelliJ suggestions. 
There are a couple of small refactors along the way.

### CODE REVIEW

**Review by Alastors — APPROVED** [review]
I didn't notice anything out of the ordinary, good job once again Chill!

**Comment by chill-was-taken** [comment]
Added Java 16 syntax through Jabel.

**Comment by wlhlm** [comment]
Can you fix Alastor's typos in the README? Thanks!

**Comment by chill-was-taken** [comment]
> Can you fix Alastor's typos (and capitalization) in the README? Thanks!

Will do. Will also resolve the merge conflicts.

**Comment by chill-was-taken** [comment]
Resolved conflicts by rebasing on master. Fixed Readme.
Essentially, the only changes are the two last commits: https://github.com/GTNewHorizons/ThaumicHorizons/pull/43/commits/801a7f78a3bb47ed26d790412b1fe19590018480 and https://github.com/GTNewHorizons/ThaumicHorizons/pull/43/commits/2ecc5e7c35d74ac116af04e4bb77efb39f6aa8f0.

**Pull request merged**
