### PR TITLE
Teleporter rebalance

### PR DESCRIPTION
**Pull request by Dream-Master**
change(Thauic Horizons)recipes changes around The Pocket Plane
add GT item to recipes via code because it cant be done vie Minetweaker (the two recipe for the Keyston overlapped)
add GT lib

### CODE REVIEW

**Comment by Dream-Master** [comment]
image
image
image
image

**Comment by KiloJoel** [comment]
Is that 2 different recipes added for the blank planar keystone?

**Review by KiloJoel — COMMENTED** [review]
> 
> 
> Is that 2 different recipes added for the blank planar keystone?

In 2.0.9.0, nei is showing only this recipe. So I believe the first of those 2 recipes makes more sense to add
image

**Comment by KiloJoel** [comment]
> 
> In 2.0.9.0, nei is showing only this recipe. So I believe the first of those 2 recipes makes more sense to add

Never mind, found this, but I still think only 1 recipe is needed
image

**Comment by Dream-Master** [comment]
@KiloJoel there are 2 recipes. The first one unlocked earlier and the second one is unlocked later on. Read the pages in the Book. All explained there.

**Comment by bartimaeusnek** [comment]
Pocket Plane Dim isnt a teleport. this doesnt make sense.

**Comment by repo-alt** [comment]
Did you read TP rebalance discussion? You may have several exits from the pocket dim. Isn't is broken on servers though?

**Review by KiloJoel — APPROVED** [review]
All looks good. Maybe worth noting that the leviathan and clouds researches were never implemented, so currently do nothing.

**Comment by KiloJoel** [comment]
> 
> 
> Pocket Plane Dim isnt a teleport. this doesnt make sense.

It's unfortunate that it can be used as one, but that is the case

**Pull request merged**
